# Generated by Django 4.2.3 on 2023-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(max_length=50, verbose_name='Main Title')),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dish Name')),
                ('content', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images/FoodPics', verbose_name='Picture')),
                ('category', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Launch', 'Launch'), ('Dinner', 'Dinner')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Name', models.CharField(max_length=50)),
                ('Contact_Email', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.CharField(max_length=50, verbose_name='Main Title')),
                ('Description', models.TextField()),
                ('News_image', models.ImageField(upload_to='images/News_Pics', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50, verbose_name='Name')),
                ('Email', models.TextField()),
                ('Password', models.CharField(max_length=16)),
                ('USER_Id', models.ImageField(upload_to='images/User_Ids', verbose_name='Id Photo')),
                ('Profile', models.ImageField(default='images/avatar.png', upload_to='images/User_Profiles', verbose_name='Profile Photo')),
            ],
        ),
    ]
