# Generated by Django 3.2.20 on 2023-08-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='USER_Id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FullName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Profile',
        ),
    ]
