# Generated by Django 3.2.20 on 2023-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.TextField(),
        ),
    ]
