# Generated by Django 4.2.3 on 2023-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='User', max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
