# Generated by Django 4.2.3 on 2023-08-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_user_username_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
