# Generated by Django 4.2.3 on 2023-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_food_amount_alter_blog_table_alter_messages_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
