# Generated by Django 4.2.3 on 2023-08-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_message_email_alter_message_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
