# Generated by Django 3.2.20 on 2023-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.TextField(),
        ),
    ]
